language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -q -r requirements.pip
env:
  - "RUNTESTS=nosetests"
  - "RUNTESTS='nosetests --tests pyxform/tests_v1/'"
script: python setup.py $RUNTESTS
notifications:
  irc: "irc.freenode.org#moditest"
